name: SnapBuy CI Pipeline

on: [push, pull_request] # Runs on every push and pull request

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run a linter (code style checker)
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      # Step 5: Run tests
      - name: Run tests
        run: npm test

      # Step 6: Security audit
      - name: Run security audit
        run: npm audit --audit-level high
